export enum OrderStageType {
    CREATED = "CREATED",
    PACKAGED = "PACKAGED",
    PROCESSED = "PROCESSED",
    SHIPPED = "SHIPPED",
    DELIVERED = "DELIVERED",
    RETURNINITIATED = "RETURNINITIATED",
    RETURNED = "RETURNED",
    RETURNEDREFUNDED = "RETURNEDREFUNDED"
}
